spring:
  application:
    name: user-service
  jackson:
    deserialization:
      fail-on-unknown-properties: false

logging:
  pattern:
    level: "%5p [%X{correlationId}]"
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect